name: Tests
on: push
jobs:
  tests:
    name: Python 3.10
    uses: Informasjonsforvaltning/workflows/.github/workflows/test-nox.yaml@main
    with:
      python_version: "3.10"
      python_architecture: x64
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
